#!/usr/bin/env node
/**
 * load-index.js
 * Load forgebee/INDEX.md into the session as additionalContext on SessionStart.
 *
 * The index gives Claude a routing map across 115+ surfaces (skills, agents,
 * commands) without having to scan each frontmatter individually.
 *
 * Generated by scripts/build-index.js — never hand-edit INDEX.md.
 */

const fs = require('fs');
const path = require('path');
const { findForgebeeRoot, output } = require('./_common.js');

function main() {
  try {
    const forgebeeRoot = findForgebeeRoot();
    const indexFile = path.join(forgebeeRoot, 'INDEX.md');

    if (!fs.existsSync(indexFile)) {
      // INDEX.md missing — never block session, just exit silently.
      // The user can run `node scripts/build-index.js` to generate it.
      process.exit(0);
    }

    const content = fs.readFileSync(indexFile, 'utf8');

    // Wrap so it's clear to Claude this is the routing reference, not the
    // skill/agent/command bodies themselves.
    const wrapped = [
      '## ForgeBee Routing Index (loaded from forgebee/INDEX.md)',
      '',
      'Use this index to route user intent to the right skill/agent/command.',
      'Skill bodies are NOT in this index — they load on invocation.',
      '',
      content,
    ].join('\n');

    output({
      hookSpecificOutput: {
        hookEventName: 'SessionStart',
        additionalContext: wrapped,
      },
    });
  } catch (e) {
    // Never block session start
    process.exit(0);
  }
}

main();
